version: '3.8'
services:
  web:
    build: .
    ports:
      - "8090:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vuln_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
    networks:
      - vuln_network

networks:
  vuln_network:
    driver: bridge
